version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - .:/opt/app
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.1-fpm
    volumes:
        - .:/opt/app